# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import GetDqnDataApi_pb2 as GetDqnDataApi__pb2


class UseDQNStub(object):
    """定义可以被远程调用的函数
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQValues = channel.unary_unary(
                '/UseDQN/GetQValues',
                request_serializer=GetDqnDataApi__pb2.Request.SerializeToString,
                response_deserializer=GetDqnDataApi__pb2.Response.FromString,
                )


class UseDQNServicer(object):
    """定义可以被远程调用的函数
    """

    def GetQValues(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UseDQNServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQValues': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQValues,
                    request_deserializer=GetDqnDataApi__pb2.Request.FromString,
                    response_serializer=GetDqnDataApi__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'UseDQN', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UseDQN(object):
    """定义可以被远程调用的函数
    """

    @staticmethod
    def GetQValues(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/UseDQN/GetQValues',
            GetDqnDataApi__pb2.Request.SerializeToString,
            GetDqnDataApi__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
