# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GetDqnDataApi.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13GetDqnDataApi.proto\"\x90\x02\n\x07Request\x12\"\n\x05state\x18\x01 \x03(\x0b\x32\x13.Request.nodeMatric\x12\x0e\n\x06reward\x18\x02 \x01(\x01\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\x05\x12&\n\tnextState\x18\x04 \x03(\x0b\x32\x13.Request.nodeMatric\x12\x0e\n\x06labels\x18\x05 \x03(\t\x12\x13\n\x0b\x66ilterNodes\x18\x06 \x03(\t\x12&\n\x07nodeMap\x18\x07 \x03(\x0b\x32\x15.Request.NodeMapEntry\x1a\x1c\n\nnodeMatric\x12\x0e\n\x06metric\x18\x01 \x03(\x01\x1a.\n\x0cNodeMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"\x1b\n\x08Response\x12\x0f\n\x07qValues\x18\x01 \x03(\x05\x32-\n\x06UseDQN\x12#\n\nGetQValues\x12\x08.Request\x1a\t.Response\"\x00\x42\nZ\x08./;protob\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_REQUEST_NODEMATRIC = _REQUEST.nested_types_by_name['nodeMatric']
_REQUEST_NODEMAPENTRY = _REQUEST.nested_types_by_name['NodeMapEntry']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {

  'nodeMatric' : _reflection.GeneratedProtocolMessageType('nodeMatric', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_NODEMATRIC,
    '__module__' : 'GetDqnDataApi_pb2'
    # @@protoc_insertion_point(class_scope:Request.nodeMatric)
    })
  ,

  'NodeMapEntry' : _reflection.GeneratedProtocolMessageType('NodeMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _REQUEST_NODEMAPENTRY,
    '__module__' : 'GetDqnDataApi_pb2'
    # @@protoc_insertion_point(class_scope:Request.NodeMapEntry)
    })
  ,
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'GetDqnDataApi_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)
_sym_db.RegisterMessage(Request.nodeMatric)
_sym_db.RegisterMessage(Request.NodeMapEntry)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'GetDqnDataApi_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

_USEDQN = DESCRIPTOR.services_by_name['UseDQN']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./;proto'
  _REQUEST_NODEMAPENTRY._options = None
  _REQUEST_NODEMAPENTRY._serialized_options = b'8\001'
  _REQUEST._serialized_start=24
  _REQUEST._serialized_end=296
  _REQUEST_NODEMATRIC._serialized_start=220
  _REQUEST_NODEMATRIC._serialized_end=248
  _REQUEST_NODEMAPENTRY._serialized_start=250
  _REQUEST_NODEMAPENTRY._serialized_end=296
  _RESPONSE._serialized_start=298
  _RESPONSE._serialized_end=325
  _USEDQN._serialized_start=327
  _USEDQN._serialized_end=372
# @@protoc_insertion_point(module_scope)
